### ISSUE TITLE
Failed to load plugin: mtg-melodia:melodia

### ISSUE THREAD

**Issue by AnganaB** [justinsalamon/audio_to_midi_melodia#10]
How do I use melodia in Jupyter notebook?

**Comment by justinsalamon** [comment]
For a tutorial on using melodia in python please see: http://www.justinsalamon.com/news/melody-extraction-in-python-with-melodia

Based on the title of this issue I'm guessing you're also getting an error which might have already been addressed in #4, please have a look and see if that resolves your issue. If not please post a full description of your issue including your OS, python environment, the exact code that resulted in the error and the full error message. Thanks!

**Comment by YuHsin1998** [comment]
$ python audio_to_midi_melodia.py a.wav b.mid 60 --smooth 0.25 --minduration 0.1 --jams
Loading audio...
Extracting melody f0 with MELODIA...
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "mtg-melodia:melodia"
Traceback (most recent call last):
  File "audio_to_midi_melodia.py", line 217, in <module>
    savejams=args.jams)
  File "audio_to_midi_melodia.py", line 166, in audio_to_midi_melodia
    parameters={"voicing": 0.2})
  File "/usr/local/lib/python2.7/dist-packages/vamp/collect.py", line 166, in collect
    plugin, step_size, block_size = vamp.load.load_and_configure(data, sample_rate, plugin_key, parameters, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vamp/load.py", line 83, in load_and_configure
    vampyhost.ADAPT_CHANNEL_COUNT)
TypeError: Failed to load plugin: mtg-melodia:melodia
why this is happening?

**Comment by YuHsin1998** [comment]
> For a tutorial on using melodia in python please see: http://www.justinsalamon.com/news/melody-extraction-in-python-with-melodia
> 
> Based on the title of this issue I'm guessing you're also getting an error which might have already been addressed in #4, please have a look and see if that resolves your issue. If not please post a full description of your issue including your OS, python environment, the exact code that resulted in the error and the full error message. Thanks!



> For a tutorial on using melodia in python please see: http://www.justinsalamon.com/news/melody-extraction-in-python-with-melodia
> 
> Based on the title of this issue I'm guessing you're also getting an error which might have already been addressed in #4, please have a look and see if that resolves your issue. If not please post a full description of your issue including your OS, python environment, the exact code that resulted in the error and the full error message. Thanks!

$ python audio_to_midi_melodia.py a.wav b.mid 60 --smooth 0.25 --minduration 0.1 --jams
Loading audio...
Extracting melody f0 with MELODIA...
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "mtg-melodia:melodia"
Traceback (most recent call last):
File "audio_to_midi_melodia.py", line 217, in 
savejams=args.jams)
File "audio_to_midi_melodia.py", line 166, in audio_to_midi_melodia
parameters={"voicing": 0.2})
File "/usr/local/lib/python2.7/dist-packages/vamp/collect.py", line 166, in collect
plugin, step_size, block_size = vamp.load.load_and_configure(data, sample_rate, plugin_key, parameters, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/vamp/load.py", line 83, in load_and_configure
vampyhost.ADAPT_CHANNEL_COUNT)
TypeError: Failed to load plugin: mtg-melodia:melodia
why this is happening?

**Comment by regisamichiafox** [comment]
hello @justinsalamon I just installed audio to melodia and I am trying to use it on Windows but I have the same problem as @YuHsin1998 . I tried to visualize the mtg-melodia plugin in sonic visualizer and I had no problem. I am running my code in an virtual environment of Anaconda. I put a copy of the melodia plugin in the 'site-packages of my virtual environment. But I am stuck and I don't have any solution. Thanks a lot in advance for your answer.

**Comment by MrAw3someness** [comment]
I think per the README, the program requires Python 2.7.

**Comment by davidloq** [comment]
> hello @justinsalamon I just installed audio to melodia and I am trying to use it on Windows 64 bits with python 3.6 but I have the same problem as @YuHsin1998 . I tried to visualize the mtg-melodia plugin in sonic visualizer and I had no problem. I am running my code in an virtual environment of Anaconda (so I write the following command in Anaconda Prompt: python audio_to_midi_melodia.py a.wav test.mid 60 --smooth 0.25 --minduration 0.1 --jams) I put a copy of the melodia plugin in the 'site-packages of my virtual environment. But I am stuck and I don't have any solution. Thanks a lot in advance for your answer.

So did you find out how to install in your virtual environment? I'am getting the same issue :(

**Comment by justinsalamon** [comment]
@YuHsin1998 what environment are you using? This script is only supported for 32-bit python 2.7. Also make sure you've installed the melodia plugin as per the instructions in the README file.

@regisamichiafox see above.

Please let me know if you manage to get it working. If not, please specify exactly how your environment is set up, the command your are trying to run, and paste the complete error message you're getting.

**Comment by YuriyPomaznoy** [comment]
32-bit python 2.7 - the same problem

**Comment by YuriyPomaznoy** [comment]
Sorry, it works
