### ISSUE TITLE
Audioread NoBackendError

### ISSUE THREAD

**Issue by hideodaikoku** [justinsalamon/audio_to_midi_melodia#15]
I tried running the code using the sample command, in order to open a .wav file for execution and ran into this error. I'm running on a Linux system with Python 2.7 and I have all the dependencies installed. 

I even have `ffmpeg` and other dependencies that work around the audioread error. Should I be using other ways to open the audio file, and note `Librosa.load()`

> Loading audio...
> Traceback (most recent call last):
>   File "audio_to_midi_melodia.py", line 210, in <module>
>     savejams=args.jams)
>   File "audio_to_midi_melodia.py", line 154, in audio_to_midi_melodia
>     data, sr = librosa.load(infile, sr=fs, mono=True)
>   File "/usr/local/lib/python2.7/site-packages/librosa/core/audio.py", line 119, in load
>     with audioread.audio_open(os.path.realpath(path)) as input_file:
>   File "/usr/local/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
>     raise NoBackendError()
> audioread.NoBackendError

**Comment by justinsalamon** [comment]
I'll soon be replacing librosa with a lighter library to load audio, which might resolve your issue. Stay tuned.

**Comment by hideodaikoku** [comment]
thanks so much for looking into it. i know this isn't strictly speaking an issue with this repo, but an issue with Audioread!

**Comment by justinsalamon** [comment]
OK I just pushed an update (v0.0.3) which doesn't rely on librosa for loading the audio. Please try the latest version and let me know if you still have any issues. Thanks.

**Comment by justinsalamon** [comment]
Stale, closing out.
