### ISSUE TITLE
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "mtg-melodia:melodia"

### ISSUE THREAD

**Issue by SiRi000** [justinsalamon/audio_to_midi_melodia#18]
hello :D 
when i run this code from cmd i always get this error 

Loading audio...
Extracting melody f0 with MELODIA...
Vamp::HostExt::PluginLoader: No library found in Vamp path for plugin "mtg-melodia:melodia"
Traceback (most recent call last):
  File "audio_to_midi_melodia.py", line 225, in <module>
    savejams=args.jams)
  File "audio_to_midi_melodia.py", line 174, in audio_to_midi_melodia
    parameters={"voicing": 0.2})
  File "C:\Python27\lib\site-packages\vamp\collect.py", line 166, in collect
    plugin, step_size, block_size = vamp.load.load_and_configure(data, sample_rate, plugin_key, parameters, **kwargs)
  File "C:\Python27\lib\site-packages\vamp\load.py", line 83, in load_and_configure
    vampyhost.ADAPT_CHANNEL_COUNT)
TypeError: Failed to load plugin: mtg-melodia:melodia

i installed vamp and melodia , i work by python 2.7 And visual studio code and installed sonic to try the plugin and its work but when it comes to python it say no library found in vamp 

could u help me please solve this issue , i'm using this code in my graduation project and the deadline is soon :(

**Comment by justinsalamon** [comment]
@cannam any idea what's happening here?

@SiRi000 can you please provide a complete description of your system (operating system, python installation, etc.)? In the meanwhile you could try [Sonic Annotator](https://www.vamp-plugins.org/sonic-annotator/) for batch processing, though it will return the extracted melody lines without the subsequent conversion to MIDI.

**Comment by cannam** [comment]
My first guess would be that the plugin is in the wrong location - if it's a 32-bit plugin being installed on 64-bit Windows, then it usually needs to go in "C:\Program Files (x86)\Vamp Plugins" and not in "C:\Program Files\Vamp Plugins". Could that be it?

**Comment by SiRi000** [comment]
> My first guess would be that the plugin is in the wrong location - if it's a 32-bit plugin being installed on 64-bit Windows, then it usually needs to go in "C:\Program Files (x86)\Vamp Plugins" and not in "C:\Program Files\Vamp Plugins". Could that be it?

thanks dude that worked for mr :D

**Comment by justinsalamon** [comment]
Cheers @cannam for the quick catch, glad issue is resolved.
