### ISSUE TITLE
how to set the program as ‘monophonic’

### ISSUE THREAD

**Issue by PageCollins** [justinsalamon/audio_to_midi_melodia#19]
I used this plugin in SV （windows），and found that the monophonic worked better than polyphonic.
if i want to set the program in python,which parameters should i send.
thank you.

**Comment by justinsalamon** [comment]
c.f. section "3.4 Extracting the melody using Melodia with custom parameter values" of this tutorial: http://www.justinsalamon.com/news/melody-extraction-in-python-with-melodia

Changing the settings in SV from "polyphonic" to "monophonic" just changes the values used for the 4 parameters shown in that section (minfqr, maxfqr, voicing, minpeaksalience), so just have a look to see what values are used when you select the "monophonic" setting and provide those values in the parameters dictionary as in the example in the aforementioned tutorial.

Once you've tried this please post a comment to confirm whether this addressed your question, thanks.

**Comment by PageCollins** [comment]
I have taken your advice and modified the parameters according to the tutorial, but the result has not changed.In the SV, notes in the bass area can be recognised by using monophonic, but this does not seem to be possible in python.

**Comment by justinsalamon** [comment]
Both SV and the python package use exactly the same vamp plugin under the hood, so the output should be identical. If it's not identical, it means either (1) the parameters being used aren't the same or (2) there's something else that's different in your pipeline (audio loading, sampling rate, etc.).

If you can paste a link here to the audio file you're analyzing, and the parameter values you're using in SV, I can try and look into it further.

**Comment by PageCollins** [comment]
the python's parameter values:
params = {"minfqr": 55.0, "maxfqr": 1760.0, "voicing": 0.2, "minpeaksalience": 0.0}
and the audio file is named 'dan.wav',SV's setting show in two pictures.
[collins.zip](https://github.com/justinsalamon/audio_to_midi_melodia/files/3460036/collins.zip)

**Comment by justinsalamon** [comment]
Those are the parameter values used for the polyphonic setting. For the monophonic setting you need to increase `voicing` from 0.2 to 3.0. 

This should be reflected in the SV interface when choosing monophonic, but there seems to be a bug in the recent releases. I just checked this using SV 2.0, where indeed the change is visible.

Please try changing the voicing parameter as noted above and let me know if it works, thanks.

**Comment by justinsalamon** [comment]
I've posted an issue on SV: https://code.soundsoftware.ac.uk/issues/1903

**Comment by PageCollins** [comment]
That's the right thing to do.Parameters were adjusted to "voicing": 3.0 to obtain accurate results.
thanks a lot.

**Comment by justinsalamon** [comment]
Great, thanks for confirming.
