### ISSUE TITLE
Melodia plugin download link has disappeared

### ISSUE THREAD

**Issue by JCBrouwer** [justinsalamon/audio_to_midi_melodia#21]
Hello, I'm trying to get this up and running but cannot seem to download the Melodia plugin from the linked site: http://mtg.upf.edu/technologies/melodia

It seems the site has undergone some changes as the above link resolves to: https://www.upf.edu/web/mtg/melodia instead.

Then, the DOWNLOAD FORM link on that page (which should go to http://mtg.upf.edu/descargas/node/1/) redirects back to the homepage (https://www.upf.edu/web/mtg/) presumably because the download form has been moved or deleted.

Where can I download this plugin?

**Comment by daxiangpanda** [comment]
same problem too!solved?

**Comment by daxiangpanda** [comment]
https://zenodo.org/record/1289780#.XYx4ey2B3OQ

**Comment by justinsalamon** [comment]
Updated download form: https://forms.gle/W78mUsiQdZvAP7gK8
