### ISSUE TITLE
Could you please tell me how to solve this problem when I install vamp?

### ISSUE THREAD

**Issue by Wud1** [justinsalamon/audio_to_midi_melodia#22]
Building wheels for collected packages: vamp
  Building wheel for vamp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/wudi/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"'; __file__='"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-wheel-g5w1jhhq --python-tag cp37
       cwd: /private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/vamp
  copying vamp/collect.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
  copying vamp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
  copying vamp/frames.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
  copying vamp/process.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
  copying vamp/load.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
  running build_ext
  building 'vampyhost' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk
  creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src
  creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src/vamp-hostsdk
  creating build/temp.macosx-10.7-x86_64-3.7/native
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/wudi/anaconda3/include -arch x86_64 -I/Users/wudi/anaconda3/include -arch x86_64 -D_USE_MATH_DEFINES=1 -Ivamp-plugin-sdk -I/Users/wudi/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/wudi/anaconda3/include/python3.7m -c vamp-plugin-sdk/src/vamp-hostsdk/Files.cpp -o build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src/vamp-hostsdk/Files.o
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from vamp-plugin-sdk/src/vamp-hostsdk/Files.cpp:37:
  In file included from vamp-plugin-sdk/vamp-hostsdk/PluginHostAdapter.h:41:
  In file included from vamp-plugin-sdk/vamp-hostsdk/Plugin.h:45:
  vamp-plugin-sdk/vamp-sdk/Plugin.h:40:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for vamp
  Running setup.py clean for vamp
Failed to build vamp
Installing collected packages: vamp
    Running setup.py install for vamp ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/wudi/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"'; __file__='"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-record-l27rp7lh/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/vamp
    copying vamp/collect.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
    copying vamp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
    copying vamp/frames.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
    copying vamp/process.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
    copying vamp/load.py -> build/lib.macosx-10.7-x86_64-3.7/vamp
    running build_ext
    building 'vampyhost' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk
    creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src
    creating build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src/vamp-hostsdk
    creating build/temp.macosx-10.7-x86_64-3.7/native
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/wudi/anaconda3/include -arch x86_64 -I/Users/wudi/anaconda3/include -arch x86_64 -D_USE_MATH_DEFINES=1 -Ivamp-plugin-sdk -I/Users/wudi/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/wudi/anaconda3/include/python3.7m -c vamp-plugin-sdk/src/vamp-hostsdk/Files.cpp -o build/temp.macosx-10.7-x86_64-3.7/vamp-plugin-sdk/src/vamp-hostsdk/Files.o
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from vamp-plugin-sdk/src/vamp-hostsdk/Files.cpp:37:
    In file included from vamp-plugin-sdk/vamp-hostsdk/PluginHostAdapter.h:41:
    In file included from vamp-plugin-sdk/vamp-hostsdk/Plugin.h:45:
    vamp-plugin-sdk/vamp-sdk/Plugin.h:40:10: fatal error: 'string' file not found
    #include <string>
             ^~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/wudi/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"'; __file__='"'"'/private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-install-5ugefj3b/vamp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/08/mzdfs5294rq4rvhtwh21xrk80000gn/T/pip-record-l27rp7lh/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by justinsalamon** [comment]
Sorry this is outside the scope of this script, please seek help with the vamp developers directly.
