### ISSUE TITLE
Failed to load plugin: mtg-melodia:melodia

### ISSUE THREAD

**Issue by Vivever** [justinsalamon/audio_to_midi_melodia#23]
The plugin fails to load in python but works in sonic visualizer. 
System particulars-
Windows10, Python 3.6
@justinsalamon 
![72747136_484341515494024_8202260518761660416_n](https://user-images.githubusercontent.com/44516722/67139117-ec369a00-f269-11e9-86b2-5967db3c3ca0.jpg)
![73528735_718630708606750_4895631022240038912_n](https://user-images.githubusercontent.com/44516722/67139119-efca2100-f269-11e9-979a-a9baa06c06e8.jpg)

**Comment by anurag-thapad** [comment]
I am facing the same issue.

**Comment by MrAw3someness** [comment]
I think per the README, the program requires Python 2.7 instead of Python 3.

**Comment by justinsalamon** [comment]
@Vivever it appears you're not actually using `audio_to_midi_melodia` (the code in this repo), just the melodia plugin with the vamp python module.

Have you tried running it in a 32-bit python 2.7 environment?
