### ISSUE TITLE
error when installing dependencies

### ISSUE THREAD

**Issue by eric0521** [justinsalamon/audio_to_midi_melodia#24]
Hi, i just bumped into some error when i used "python2 -m pip install -r requirements.txt" in cmd, 
![image](https://user-images.githubusercontent.com/64369535/80631018-b62f6980-8a87-11ea-87cc-64e6be60de2b.png) I've tried to google about installing llvmlite but still can't fix it.

python version: 2.7.18
windows10

**Comment by ShivamGarg2910** [comment]
Hi, I get the same error while trying to install resampy.
Python version 2.7.16 32bit
OS: windows 10

**Comment by Inky1003** [comment]
I've tried this and llvmlite installed to me:
`python -m pip install pip install llvmlite==0.31.0`
don't forget that Microsoft Visual C++ 9.0 is required. [Get It here](http://aka.ms/vcpython27) 
Then do the requirements again

**Comment by justinsalamon** [comment]
Thanks for posting a solution @Inky1003 ! Closing this out.
