### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int' AND struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by rmabbey** [justinsalamon/audio_to_midi_melodia#5]
Finding this software was a life saver! I'm just struggling to get it to work currently. I'm trying to use it for a research project where I need a large data set of midi files of melodies of songs so this functionality is pretty perfect.

I encountered a type error when executing the command below in my terminal.
```
$ python3 audio_to_midi_melodia_master/audio_to_midi_melodia.py watchwhathappens.wav watchwhathappens.mid 172
Loading audio...
Extracting melody f0 with MELODIA...
Converting Hz to MIDI notes...
audio_to_midi_melodia_master/audio_to_midi_melodia.py:142: RuntimeWarning: divide by zero encountered in log2
  midi = 69 + 12*np.log2(hz_nonneg/440.)
Traceback (most recent call last):
  File "audio_to_midi_melodia_master/audio_to_midi_melodia.py", line 216, in <module>
    savejams=args.jams)
  File "audio_to_midi_melodia_master/audio_to_midi_melodia.py", line 182, in audio_to_midi_melodia
    notes = midi_to_notes(midi_pitch, fs, hop, smooth, minduration)
  File "audio_to_midi_melodia_master/audio_to_midi_melodia.py", line 114, in midi_to_notes
    if p_prev > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
I traced it back to the following code in the `midi_to_notes` function:
```
    notes = []
    p_prev = None
    duration = 0
    onset = 0
    for n, p in enumerate(midi_filt):
        if p == p_prev:
            duration += 1
        else:
            # treat 0 as silence
            if p_prev > 0:
                # add note
                duration_sec = duration * hop / float(fs)
                # only add notes that are long enough
                if duration_sec >= minduration:
                    onset_sec = onset * hop / float(fs)
                    notes.append((onset_sec, duration_sec, p_prev))

            # start new note
            onset = n
            duration = 1
            p_prev = p
```
In the for loop, the `else` part of the if condition evaluates `p_prev` before it's been set to the current `p`, which gives an error in the first iteration of the loop when `p_prev = None` from initialisation. 

I think this can be solved by changing `p_prev` to `p` in the lines `if p_prev > 0` and `notes.append((onset_sec, duration_sec, p_prev))`. 

I tried creating a new script and amending this and then I received the following error in my terminal:
```
$ python3 audio_to_midi_melodia_master/new_script.py watchwhathappens.wav watchwhathappens.mid 172
Loading audio...
Extracting melody f0 with MELODIA...
Converting Hz to MIDI notes...
audio_to_midi_melodia_master/new_script.py:144: RuntimeWarning: divide by zero encountered in log2
  midi = 69 + 12*np.log2(hz_nonneg/440.)
Saving MIDI to disk...
Traceback (most recent call last):
  File "audio_to_midi_melodia_master/new_script.py", line 220, in <module>
    savejams=args.jams)
  File "audio_to_midi_melodia_master/new_script.py", line 190, in audio_to_midi_melodia
    save_midi(outfile, notes, bpm)
  File "audio_to_midi_melodia_master/new_script.py", line 88, in save_midi
    midifile.writeFile(binfile)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/midiutil/MidiFile.py", line 1637, in writeFile
    self.close()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/midiutil/MidiFile.py", line 1699, in close
    self.tracks[i].writeMIDIStream()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/midiutil/MidiFile.py", line 835, in writeMIDIStream
    self.writeEventsToStream()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/midiutil/MidiFile.py", line 852, in writeEventsToStream
    self.MIDIdata += event.serialize(previous_event_tick)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/midiutil/MidiFile.py", line 124, in serialize
    midibytes += struct.pack('>B', self.pitch)
struct.error: required argument is not an integer
```
I realised that the resulting `midi` array returned from `hz2midi` has float elements, but I tried converting them to integers and I still get the same error and cannot get around it.

Am I doing something really wrong? I can't seem to figure out how to solve this.

Thanks in advance!
xxx

**Comment by dewhisna** [comment]
I had this same problem but found that switching from python3 to python2.7 (2.7.13 on Debian to be exact) worked.  I think some of the supporting libraries haven't been updated yet to work correctly in python3.

**Comment by justinsalamon** [comment]
Thanks @rmabbey for reporting this and @dewhisna for commenting. Indeed, the script was only tested on python 2.7 and may not work on python 3 (sorry for not specifying this in the README, will do so ASAP). The easiest solution is to create a python 2.7 environment using [conda](https://conda.io/docs/index.html) and run the script from within this environment.

**Comment by justinsalamon** [comment]
@rmabbey did using to python 2.7 solve your issue?

**Comment by roedoejet** [comment]
I changed `p_prev = None` to ` p_prev = 0` and I'm at least not getting any errors running on Python 3...

**Comment by DavidParkin** [comment]
Right, here goes. Same problem, got round it with p_prev = 0 and by extracting the integer value from pitch before calling midifile.addnote. Used pitch.__int__ which I believe doesn't impress python people, but it works. I guess python3 is less willing to convert types.
Ran it with --jams,  --minduration and --smooth. 
I may have put in a valid pull request but is available on my repo. (Anything to save adding more python2.7)

**Comment by justinsalamon** [comment]
Closing out as this is not an issue on the currently supported versions of python (2.7). Opened #8 to add python 3 support.
