### ISSUE TITLE
Having trouble getting to work

### ISSUE THREAD

**Issue by YukiSakuma** [justinsalamon/audio_to_midi_melodia#6]
Fixed.

**Comment by justinsalamon** [comment]
@YukiSakuma for posterity (and helping others who may have issues in the future) would you mind posting here what the problem was, and how you solved it? Thanks!

**Comment by YukiSakuma** [comment]
The problem was installing the requirements specifically the vamp whl file
I had to install python 2.7 32 bit to be able to install that whl file and using the appropriate install command like `-2.7`
Anyway it took me hours to figure it out 
:sweat_smile:
