### ISSUE TITLE
Divide by zero in log2 calculation

### ISSUE THREAD

**Issue by dewhisna** [justinsalamon/audio_to_midi_melodia#7]
Regardless of the source audio, I get the following warning:
```
audio_to_midi_melodia.py:142: RuntimeWarning: divide by zero encountered in log2
  midi = 69 + 12*np.log2(hz_nonneg/440.)
```

In this code block:
```
def hz2midi(hz):

    # convert from Hz to midi note
    hz_nonneg = hz.copy()
    hz_nonneg[hz <= 0] = 0
    midi = 69 + 12*np.log2(hz_nonneg/440.)
    midi[midi <= 0] = 0

    # round
    midi = np.round(midi)

    return midi
```

To silence the warning, I edited that to initialize the other entries to a very small value instead of 0, changing that line above the warning to be:
```
    hz_nonneg[hz <= 0] = 1.e-15;
```

I don't know if that's the preferred fix or not, as I haven't fully checked to see how it affects the remaining code, but it seems to work OK to get rid of that warning.  And the resulting midi files, on the ones that I checked, were identical with or without the fix.

Otherwise, this script and the Melodia plugin work fantastically!  Great job with it!

**Comment by justinsalamon** [comment]
Melodia indicates unvoiced frames with non-positive (negative or zero) values. The hz2midi function sets these to 0 before taking the log, which will return -Inf, and then resets these values to 0 again after taking the log. This is the intended behavior. I could probably achieve the same result more elegantly so as to avoid the warning, but the overall functionality is correct.

**Comment by justinsalamon** [comment]
Updated the conversion code to avoid the warnings 4821cde1b1cf26c736a0da01ca7b9f4b01786884
